# GitHub Action for generating a contribution graph
name: Generate Snake Animation

on:
  schedule:
    # Runs every 6 hours
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate Snake Animation
        uses: Platane/snk@v2
        with:
          github_user_name: ravindulakruwan
          # list of paths to comma-separated svgs (or a single path)
          svg_out_path: github-contribution-grid-snake.svg

      - name: Push new animation
        uses: crazy-max/ghaction-github-pages@v2.5.0
        with:
          target_branch: main
          build_dir: .
          commit_message: "Update snake animation"
          keep_history: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
